package proyectoaereopuerto;

/**
 *
 * @author Hakris
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     
     */
    public MenuUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtn_NuevoVuelo = new javax.swing.JButton();
        jbtn_ModificarCuenta = new javax.swing.JButton();
        jbtn_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema del Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 50));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¡Bienvenido!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 50));

        jbtn_NuevoVuelo.setBackground(new java.awt.Color(102, 204, 255));
        jbtn_NuevoVuelo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jbtn_NuevoVuelo.setForeground(new java.awt.Color(204, 255, 255));
        jbtn_NuevoVuelo.setText("Adquirir nuevo vuelo");
        jbtn_NuevoVuelo.setBorder(null);
        jbtn_NuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_NuevoVueloActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_NuevoVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 340, 50));

        jbtn_ModificarCuenta.setBackground(new java.awt.Color(102, 204, 255));
        jbtn_ModificarCuenta.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jbtn_ModificarCuenta.setForeground(new java.awt.Color(204, 255, 255));
        jbtn_ModificarCuenta.setText("Modificar mi cuenta");
        jbtn_ModificarCuenta.setBorder(null);
        jbtn_ModificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ModificarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_ModificarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 340, 50));

        jbtn_Salir.setBackground(new java.awt.Color(102, 204, 255));
        jbtn_Salir.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jbtn_Salir.setForeground(new java.awt.Color(204, 255, 255));
        jbtn_Salir.setText("Desconectarse");
        jbtn_Salir.setBorder(null);
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 340, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaereopuerto/imagenes/fondoUsuario.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_SalirActionPerformed

    private void jbtn_NuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_NuevoVueloActionPerformed
        CrearVuelos mv = new CrearVuelos();
        mv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_NuevoVueloActionPerformed

    private void jbtn_ModificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ModificarCuentaActionPerformed
        ModificarCuenta mc = new ModificarCuenta();
        mc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_ModificarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtn_ModificarCuenta;
    private javax.swing.JButton jbtn_NuevoVuelo;
    private javax.swing.JButton jbtn_Salir;
    // End of variables declaration//GEN-END:variables
}
